id = "ifc"
name = "IFC"
description = "Industry Foundation Classes (IFC) language support."
version = "0.1.0"
schema_version = 1
authors = ["Benedict Harder"]

[language_servers.ifc-language-server]
name = "IFC Language Server"
language = "IFC"

[grammars.ifc]
repository = "https://github.com/NepomukWolf/tree-sitter-ifc"
commit = "bd5039f5d7929a9a8e1c138cd449ec385f17789e"
